version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: udoit2_db
    restart: always
    environment:
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: enter123
      POSTGRES_DB: udoit2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udoit2web_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin123:enter123@db:5432/udoit2
    depends_on:
      - db

volumes:
  postgres_data: 